import { LanguageCode } from '../types';

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    appName: 'WORD HUNT',
    tagline: 'Search. Learn. Explore.',
    play: 'PLAY',
    dailyPuzzle: 'Daily Puzzle',
    collection: 'Collection',
    achievements: 'Achievements',
    awards: 'Awards',
    records: 'Records',
    streak: 'Daily Streak',
    settings: 'Settings',
    settingsSubtitle: 'Sound, haptics, theme and language',
    profile: 'Profile',
    shop: 'Shop',
    removeAds: 'Remove Ads',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    restorePurchases: 'Restore Purchases',
    world: 'World',
    level: 'Level',
    levelComplete: 'LEVEL COMPLETE!',
    nextLevel: 'NEXT LEVEL',
    share: 'SHARE',
    wordsFound: 'Words Found',
    bonusXp: 'Bonus XP',
    stars: 'Stars',
    hintLetter: 'Highlight Start',
    hintWord: 'Reveal Word',
    hintAuto: 'Auto-Solve',
    hintLetterDesc: 'Reveals starting letter of a hidden word',
    hintWordDesc: 'Shows a target word on your list',
    hintAutoDesc: 'Automatically finds and solves a word on grid',
    gameplayAudio: 'Gameplay & Audio',
    sound: 'Sound Effects',
    soundDesc: 'Acoustic clicks, swipes and completion chimes',
    music: 'Ambient Music',
    musicDesc: 'Relaxing background melody during play',
    vibration: 'Haptic Feedback',
    vibrationDesc: 'Vibrate on valid letter selection',
    appearance: 'Appearance & Display',
    darkMode: 'Dark Theme',
    highContrast: 'High Contrast Mode',
    highContrastDesc: 'Maximum contrast, bold letter borders',
    largeText: 'Larger Text',
    reducedMotion: 'Reduced Motion',
    language: 'Language',
    languageSubtitle: 'Select language for game interface & puzzles',
    about: 'About Word Hunt',
    dangerZone: 'Game Progress',
    resetProgress: 'Reset Progress to Level 1',
    resetConfirm: 'Reset all journey progress and start fresh from Level 1?',
    resetSuccess: 'Progress reset to Level 1.',
    dailyStreak: 'Daily Streak',
    claimReward: 'Claim Reward',
    streakReward: 'Streak Reward',
    puzzlesSolved: 'Puzzles Solved',
    totalWords: 'Words Discovered',
    totalStars: 'Total Stars',
    bestStreak: 'Best Streak',
    accuracy: 'Accuracy',
    saveSuccessful: 'Progress saved successfully',
    watchAdForHint: 'Watch Ad (+1 Hint)',
    buyHints: 'Get Hint Pack',
    back: 'Back',
    tapToLearn: 'Tap any found word to view its definition & example!',
    tutorialSwipe: 'Swipe across letters to find the word:',
    howToPlay: 'How to Play',
    gotIt: 'Got It!',
    copied: 'Copied to clipboard!',
    challenges: 'Challenges',
    challengeSubtitle: 'Special timed expeditions, larger grids & extra rewards',
    currentChallenge: 'Current Challenge',
    gridSize: 'Grid Size',
    difficulty: 'Difficulty',
    reward: 'Reward',
    playChallenge: 'Play Expedition',
    challengeCompleted: 'Challenge Completed',
    hints: 'Hints',
    collectionSubtitle: 'Your badges, trophies, milestones, and stats',
    unlocked: 'unlocked',
    of: 'of',
    definition: 'Definition',
    example: 'Example',
    freeHints: 'Free',
    adHint: 'Ad Hint'
  },
  es: {
    appName: 'WORD HUNT',
    tagline: 'Encuentra. Aprende. Explora.',
    play: 'JUGAR',
    dailyPuzzle: 'Puzzle Diario',
    collection: 'Colección',
    achievements: 'Logros',
    awards: 'Premios',
    records: 'Récords',
    streak: 'Racha Diaria',
    settings: 'Ajustes',
    settingsSubtitle: 'Sonido, vibración, tema e idioma',
    profile: 'Perfil',
    shop: 'Tienda',
    removeAds: 'Quitar Anuncios',
    privacy: 'Privacidad',
    terms: 'Términos',
    restorePurchases: 'Restaurar Compras',
    world: 'Mundo',
    level: 'Nivel',
    levelComplete: '¡NIVEL COMPLETADO!',
    nextLevel: 'SIGUIENTE NIVEL',
    share: 'COMPARTIR',
    wordsFound: 'Palabras Encontradas',
    bonusXp: 'XP Extra',
    stars: 'Estrellas',
    hintLetter: 'Resaltar Inicio',
    hintWord: 'Revelar Palabra',
    hintAuto: 'Resolver Auto',
    hintLetterDesc: 'Marca la letra inicial de una palabra oculta',
    hintWordDesc: 'Muestra una palabra objetivo en la lista',
    hintAutoDesc: 'Traza y resuelve automáticamente una palabra',
    gameplayAudio: 'Sonido y Jugabilidad',
    sound: 'Efectos de Sonido',
    soundDesc: 'Sonidos al trazar letras y resolver',
    music: 'Música Ambiental',
    musicDesc: 'Melodía suave y relajante de fondo',
    vibration: 'Vibración Háptica',
    vibrationDesc: 'Vibrar al seleccionar letras válidas',
    appearance: 'Apariencia y Accesibilidad',
    darkMode: 'Modo Oscuro',
    highContrast: 'Alto Contraste',
    highContrastDesc: 'Bordes marcados y mayor legibilidad',
    largeText: 'Texto Grande',
    reducedMotion: 'Animaciones Reducidas',
    language: 'Idioma',
    languageSubtitle: 'Selecciona el idioma de la interfaz y palabras',
    about: 'Acerca de Word Hunt',
    dangerZone: 'Progreso del Juego',
    resetProgress: 'Reiniciar al Nivel 1',
    resetConfirm: '¿Reiniciar todo el progreso y volver al Nivel 1?',
    resetSuccess: 'Progreso reiniciado al Nivel 1.',
    dailyStreak: 'Racha de Días',
    claimReward: 'Reclamar Premio',
    streakReward: 'Premio de Racha',
    puzzlesSolved: 'Puzzles Resueltos',
    totalWords: 'Palabras Totales',
    totalStars: 'Estrellas Ganadas',
    bestStreak: 'Mejor Racha',
    accuracy: 'Precisión',
    saveSuccessful: 'Progreso guardado',
    watchAdForHint: 'Ver Anuncio (+1 Pista)',
    buyHints: 'Pack de Pistas',
    back: 'Atrás',
    tapToLearn: '¡Toca cualquier palabra encontrada para ver su significado y ejemplo!',
    tutorialSwipe: 'Desliza sobre las letras para formar la palabra:',
    howToPlay: 'Cómo Jugar',
    gotIt: '¡Entendido!',
    copied: '¡Copiado al portapapeles!',
    challenges: 'Desafíos',
    challengeSubtitle: 'Expediciones especiales con cuadrículas grandes y premios',
    currentChallenge: 'Desafío Actual',
    gridSize: 'Tamaño',
    difficulty: 'Dificultad',
    reward: 'Premio',
    playChallenge: 'Jugar Expedición',
    challengeCompleted: 'Desafío Completado',
    hints: 'Pistas',
    collectionSubtitle: 'Tus insignias, trofeos, hitos y estadísticas',
    unlocked: 'desbloqueados',
    of: 'de',
    definition: 'Definición',
    example: 'Ejemplo',
    freeHints: 'Gratis',
    adHint: 'Anuncio'
  },
  fr: {
    appName: 'WORD HUNT',
    tagline: 'Cherchez. Apprenez. Explorez.',
    play: 'JOUER',
    dailyPuzzle: 'Défi Quotidien',
    collection: 'Collection',
    achievements: 'Succès',
    awards: 'Trophées',
    records: 'Records',
    streak: 'Série Quotidienne',
    settings: 'Paramètres',
    settingsSubtitle: 'Son, vibrations, thème et langue',
    profile: 'Profil',
    shop: 'Boutique',
    removeAds: 'Supprimer Pubs',
    privacy: 'Confidentialité',
    terms: 'Conditions',
    restorePurchases: 'Restaurer Achats',
    world: 'Monde',
    level: 'Niveau',
    levelComplete: 'NIVEAU RÉUSSI !',
    nextLevel: 'NIVEAU SUIVANT',
    share: 'PARTAGER',
    wordsFound: 'Mots Trouvés',
    bonusXp: 'Bonus XP',
    stars: 'Étoiles',
    hintLetter: 'Première Lettre',
    hintWord: 'Révéler Mot',
    hintAuto: 'Auto-Résolution',
    hintLetterDesc: 'Indique la première lettre du mot caché',
    hintWordDesc: 'Affiche un mot à chercher sur la liste',
    hintAutoDesc: 'Trouve et résout automatiquement un mot',
    gameplayAudio: 'Audio et Jouabilité',
    sound: 'Effets Sonores',
    soundDesc: 'Clics tactiles et mélodie de victoire',
    music: 'Musique d’Ambiance',
    musicDesc: 'Mélodie douce et relaxante pendant la partie',
    vibration: 'Vibrations Haptiques',
    vibrationDesc: 'Vibration lors du glissement sur les lettres',
    appearance: 'Affichage et Accessibilité',
    darkMode: 'Thème Sombre',
    highContrast: 'Contraste Élevé',
    highContrastDesc: 'Bordures nettes et lisibilité maximale',
    largeText: 'Texte Agrandie',
    reducedMotion: 'Animations Réduites',
    language: 'Langue',
    languageSubtitle: 'Choisir la langue de l’interface et des mots',
    about: 'À propos de Word Hunt',
    dangerZone: 'Progression du Jeu',
    resetProgress: 'Réinitialiser au Niveau 1',
    resetConfirm: 'Réinitialiser toute votre progression et repartir du Niveau 1 ?',
    resetSuccess: 'Progression réinitialisée au Niveau 1.',
    dailyStreak: 'Jours Consécutifs',
    claimReward: 'Récupérer',
    streakReward: 'Récompense Série',
    puzzlesSolved: 'Grilles Résolues',
    totalWords: 'Mots Découverts',
    totalStars: 'Étoiles Totales',
    bestStreak: 'Meilleure Série',
    accuracy: 'Précision',
    saveSuccessful: 'Progression enregistrée',
    watchAdForHint: 'Regarder Pub (+1 Indice)',
    buyHints: 'Pack d’Indices',
    back: 'Retour',
    tapToLearn: 'Touchez un mot trouvé pour découvrir sa définition et son exemple !',
    tutorialSwipe: 'Faites glisser votre doigt pour relier les lettres :',
    howToPlay: 'Comment Jouer',
    gotIt: 'Compris !',
    copied: 'Copié dans le presse-papier !',
    challenges: 'Défis',
    challengeSubtitle: 'Expéditions spéciales avec grandes grilles et récompenses',
    currentChallenge: 'Défi Actuel',
    gridSize: 'Taille Grille',
    difficulty: 'Difficulté',
    reward: 'Récompense',
    playChallenge: 'Lancer l’Expédition',
    challengeCompleted: 'Défi Terminé',
    hints: 'Indices',
    collectionSubtitle: 'Vos badges, trophées, jalons et statistiques',
    unlocked: 'débloqués',
    of: 'sur',
    definition: 'Définition',
    example: 'Exemple',
    freeHints: 'Gratuit',
    adHint: 'Pub'
  },
  de: {
    appName: 'WORD HUNT',
    tagline: 'Suchen. Lernen. Entdecken.',
    play: 'SPIELEN',
    dailyPuzzle: 'Tägliches Rätsel',
    collection: 'Sammlung',
    achievements: 'Erfolge',
    awards: 'Abzeichen',
    records: 'Rekorde',
    streak: 'Tages-Serie',
    settings: 'Einstellungen',
    settingsSubtitle: 'Audio, Haptik, Design und Sprache',
    profile: 'Profil',
    shop: 'Shop',
    removeAds: 'Werbung entfernen',
    privacy: 'Datenschutz',
    terms: 'Nutzungsbedingungen',
    restorePurchases: 'Käufe wiederherstellen',
    world: 'Welt',
    level: 'Level',
    levelComplete: 'LEVEL GESCHAFFT!',
    nextLevel: 'NÄCHSTES LEVEL',
    share: 'TEILEN',
    wordsFound: 'Gefundene Wörter',
    bonusXp: 'Bonus XP',
    stars: 'Sterne',
    hintLetter: 'Anfangsbuchstabe',
    hintWord: 'Wort aufdecken',
    hintAuto: 'Auto-Lösung',
    hintLetterDesc: 'Hebt den ersten Buchstaben eines versteckten Wortes hervor',
    hintWordDesc: 'Zeigt ein gesuchtes Wort auf der Liste an',
    hintAutoDesc: 'Löst automatisch ein Wort im Buchstabengitter',
    gameplayAudio: 'Audio & Steuerung',
    sound: 'Soundeffekte',
    soundDesc: 'Klang beim Buchstabenziehen und Lösen',
    music: 'Hintergrundmusik',
    musicDesc: 'Entspannende Melodie beim Rätseln',
    vibration: 'Haptisches Feedback',
    vibrationDesc: 'Vibrieren beim Auswählen von Buchstaben',
    appearance: 'Anzeige & Barrierefreiheit',
    darkMode: 'Dunkles Design',
    highContrast: 'Hoher Kontrast',
    highContrastDesc: 'Maximale Lesbarkeit mit kräftigen Kanten',
    largeText: 'Große Schrift',
    reducedMotion: 'Weniger Bewegung',
    language: 'Sprache',
    languageSubtitle: 'Sprache für Menüs und Worträtsel wählen',
    about: 'Über Word Hunt',
    dangerZone: 'Spielfortschritt',
    resetProgress: 'Auf Level 1 zurücksetzen',
    resetConfirm: 'Gesamten Spielfortschritt löschen und bei Level 1 neu starten?',
    resetSuccess: 'Fortschritt auf Level 1 zurückgesetzt.',
    dailyStreak: 'Tages-Serie',
    claimReward: 'Belohnung abholen',
    streakReward: 'Serien-Bonus',
    puzzlesSolved: 'Gelöste Rätsel',
    totalWords: 'Gefundene Wörter',
    totalStars: 'Gesamte Sterne',
    bestStreak: 'Beste Serie',
    accuracy: 'Genauigkeit',
    saveSuccessful: 'Fortschritt gespeichert',
    watchAdForHint: 'Werbung ansehen (+1 Tipp)',
    buyHints: 'Tipp-Paket holen',
    back: 'Zurück',
    tapToLearn: 'Tippe auf ein gefundenes Wort, um Erklärung und Beispielsatz zu sehen!',
    tutorialSwipe: 'Wische über Buchstaben, um das Wort zu finden:',
    howToPlay: 'Spielanleitung',
    gotIt: 'Verstanden!',
    copied: 'In die Zwischenablage kopiert!',
    challenges: 'Herausforderungen',
    challengeSubtitle: 'Spezielle Expeditionen mit großen Gittern und Extra-Belohnungen',
    currentChallenge: 'Aktuelle Herausforderung',
    gridSize: 'Gittergröße',
    difficulty: 'Schwierigkeit',
    reward: 'Belohnung',
    playChallenge: 'Expedition starten',
    challengeCompleted: 'Herausforderung beendet',
    hints: 'Tipps',
    collectionSubtitle: 'Deine Abzeichen, Trophäen, Meilensteine und Statistiken',
    unlocked: 'freigeschaltet',
    of: 'von',
    definition: 'Bedeutung',
    example: 'Beispielsatz',
    freeHints: 'Kostenlos',
    adHint: 'Werbung'
  },
  pt: {
    appName: 'WORD HUNT',
    tagline: 'Procure. Aprenda. Explore.',
    play: 'JOGAR',
    dailyPuzzle: 'Desafio Diário',
    collection: 'Coleção',
    achievements: 'Conquistas',
    awards: 'Troféus',
    records: 'Recordes',
    streak: 'Sequência Diária',
    settings: 'Configurações',
    settingsSubtitle: 'Áudio, vibração, tema e idioma',
    profile: 'Perfil',
    shop: 'Loja',
    removeAds: 'Remover Anúncios',
    privacy: 'Privacidade',
    terms: 'Termos de Uso',
    restorePurchases: 'Restaurar Compras',
    world: 'Mundo',
    level: 'Nível',
    levelComplete: 'NÍVEL CONCLUÍDO!',
    nextLevel: 'PRÓXIMO NÍVEL',
    share: 'COMPARTILHAR',
    wordsFound: 'Palavras Encontradas',
    bonusXp: 'XP Bônus',
    stars: 'Estrelas',
    hintLetter: 'Letra Inicial',
    hintWord: 'Revelar Palavra',
    hintAuto: 'Auto-Resolver',
    hintLetterDesc: 'Destaca a letra inicial de uma palavra escondida',
    hintWordDesc: 'Mostra uma palavra alvo na sua lista',
    hintAutoDesc: 'Encontra e resolve automaticamente uma palavra',
    gameplayAudio: 'Áudio e Jogabilidade',
    sound: 'Efeitos Sonoros',
    soundDesc: 'Cliques ao arrastar e som de vitória',
    music: 'Música Ambiente',
    musicDesc: 'Melodia calma e relaxante de fundo',
    vibration: 'Vibração Tátil',
    vibrationDesc: 'Vibrar ao selecionar letras corretas',
    appearance: 'Visual e Acessibilidade',
    darkMode: 'Tema Escuro',
    highContrast: 'Alto Contraste',
    highContrastDesc: 'Bordas nítidas e letras com máxima leitura',
    largeText: 'Texto Maior',
    reducedMotion: 'Reduzir Animações',
    language: 'Idioma',
    languageSubtitle: 'Escolha o idioma da interface e dos caça-palavras',
    about: 'Sobre o Word Hunt',
    dangerZone: 'Progresso do Jogo',
    resetProgress: 'Reiniciar para o Nível 1',
    resetConfirm: 'Deseja apagar todo o progresso e reiniciar no Nível 1?',
    resetSuccess: 'Progresso reiniciado para o Nível 1.',
    dailyStreak: 'Sequência de Dias',
    claimReward: 'Resgatar Recompensa',
    streakReward: 'Recompensa de Sequência',
    puzzlesSolved: 'Jogos Concluídos',
    totalWords: 'Palavras Totais',
    totalStars: 'Total de Estrelas',
    bestStreak: 'Melhor Sequência',
    accuracy: 'Precisão',
    saveSuccessful: 'Progresso salvo com sucesso',
    watchAdForHint: 'Assistir Vídeo (+1 Dica)',
    buyHints: 'Comprar Dicas',
    back: 'Voltar',
    tapToLearn: 'Toque em qualquer palavra encontrada para ver o significado e exemplo!',
    tutorialSwipe: 'Deslize pelas letras para encontrar a palavra:',
    howToPlay: 'Como Jogar',
    gotIt: 'Entendido!',
    copied: 'Copiado para a área de transferência!',
    challenges: 'Expedições',
    challengeSubtitle: 'Desafios cronometrados com grades maiores e recompensas extras',
    currentChallenge: 'Desafio Atual',
    gridSize: 'Tamanho da Grade',
    difficulty: 'Dificuldade',
    reward: 'Recompensa',
    playChallenge: 'Iniciar Expedição',
    challengeCompleted: 'Desafio Concluído',
    hints: 'Dicas',
    collectionSubtitle: 'Suas medalhas, troféus, marcos e estatísticas',
    unlocked: 'desbloqueadas',
    of: 'de',
    definition: 'Significado',
    example: 'Exemplo',
    freeHints: 'Grátis',
    adHint: 'Vídeo'
  },
  id: {
    appName: 'WORD HUNT',
    tagline: 'Cari. Pelajari. Jelajahi.',
    play: 'MAIN',
    dailyPuzzle: 'Teka-Teki Harian',
    collection: 'Koleksi',
    achievements: 'Pencapaian',
    awards: 'Penghargaan',
    records: 'Catatan Rekor',
    streak: 'Runtutan Harian',
    settings: 'Pengaturan',
    settingsSubtitle: 'Audio, getaran, tampilan, dan bahasa',
    profile: 'Profil',
    shop: 'Toko',
    removeAds: 'Hapus Iklan',
    privacy: 'Kebijakan Privasi',
    terms: 'Ketentuan Layanan',
    restorePurchases: 'Pulihkan Pembelian',
    world: 'Dunia',
    level: 'Level',
    levelComplete: 'LEVEL SELESAI!',
    nextLevel: 'LEVEL BERIKUTNYA',
    share: 'BAGIKAN',
    wordsFound: 'Kata Ditemukan',
    bonusXp: 'Bonus XP',
    stars: 'Bintang',
    hintLetter: 'Huruf Pertama',
    hintWord: 'Buka Kata',
    hintAuto: 'Selesaikan Otomatis',
    hintLetterDesc: 'Menyorot huruf awal dari kata tersembunyi',
    hintWordDesc: 'Menampilkan kata target pada daftar kata',
    hintAutoDesc: 'Menemukan dan menyelesaikan kata secara otomatis',
    gameplayAudio: 'Audio & Kontrol Permainan',
    sound: 'Efek Suara',
    soundDesc: 'Suara saat menggesek huruf dan menyelesaikan kata',
    music: 'Musik Latar',
    musicDesc: 'Melodi lembut yang menenangkan saat bermain',
    vibration: 'Getaran Haptik',
    vibrationDesc: 'Getaran saat menghubungkan huruf yang benar',
    appearance: 'Tampilan & Aksesibilitas',
    darkMode: 'Mode Gelap',
    highContrast: 'Kontras Tinggi',
    highContrastDesc: 'Kontras maksimal untuk kenyamanan membaca',
    largeText: 'Teks Besar',
    reducedMotion: 'Kurangi Gerakan',
    language: 'Bahasa',
    languageSubtitle: 'Pilih bahasa antarmuka dan teka-teki kata',
    about: 'Tentang Word Hunt',
    dangerZone: 'Progres Permainan',
    resetProgress: 'Atur Ulang ke Level 1',
    resetConfirm: 'Apakah Anda yakin ingin mengatur ulang progres ke Level 1?',
    resetSuccess: 'Progres berhasil diatur ulang ke Level 1.',
    dailyStreak: 'Runtutan Hari',
    claimReward: 'Klaim Hadiah',
    streakReward: 'Hadiah Runtutan',
    puzzlesSolved: 'Teka-Teki Selesai',
    totalWords: 'Total Kata Ditemukan',
    totalStars: 'Total Bintang',
    bestStreak: 'Runtutan Terbaik',
    accuracy: 'Akurasi',
    saveSuccessful: 'Progres berhasil disimpan',
    watchAdForHint: 'Tonton Iklan (+1 Petunjuk)',
    buyHints: 'Beli Paket Petunjuk',
    back: 'Kembali',
    tapToLearn: 'Ketuk kata yang telah ditemukan untuk membaca arti dan contoh kalimat!',
    tutorialSwipe: 'Geser jari melintasi huruf untuk menyusun kata:',
    howToPlay: 'Cara Bermain',
    gotIt: 'Mengerti!',
    copied: 'Berhasil disalin ke papan klip!',
    challenges: 'Tantangan',
    challengeSubtitle: 'Ekspedisi waktu khusus, kisi lebih luas & hadiah ekstra',
    currentChallenge: 'Tantangan Saat Ini',
    gridSize: 'Ukuran Kisi',
    difficulty: 'Tingkat Kesulitan',
    reward: 'Hadiah',
    playChallenge: 'Mulai Ekspedisi',
    challengeCompleted: 'Tantangan Selesai',
    hints: 'Petunjuk',
    collectionSubtitle: 'Lencana, trofi, tonggak sejarah, dan statistik Anda',
    unlocked: 'terbuka',
    of: 'dari',
    definition: 'Arti Kata',
    example: 'Contoh Kalimat',
    freeHints: 'Gratis',
    adHint: 'Iklan'
  },
  ja: {
    appName: 'WORD HUNT',
    tagline: '探す。学ぶ。旅をする。',
    play: 'プレイ',
    dailyPuzzle: 'デイリーパズル',
    collection: 'コレクション',
    achievements: '実績',
    awards: 'トロフィー',
    records: '記録',
    streak: 'デイリーストリーク',
    settings: '設定',
    settingsSubtitle: 'サウンド、振動、テーマ、言語',
    profile: 'プロフィール',
    shop: 'ショップ',
    removeAds: '広告を削除',
    privacy: 'プライバシーポリシー',
    terms: '利用規約',
    restorePurchases: '購入の復元',
    world: 'ワールド',
    level: 'レベル',
    levelComplete: 'ステージクリア！',
    nextLevel: '次のレベルへ',
    share: 'シェア',
    wordsFound: '見つけた単語',
    bonusXp: 'ボーナスXP',
    stars: 'スター',
    hintLetter: '最初の文字',
    hintWord: '単語を見る',
    hintAuto: '自動解決',
    hintLetterDesc: '隠れた単語の開始文字をハイライトします',
    hintWordDesc: '単語リストから1つ表示します',
    hintAutoDesc: '盤面の単語を自動で見つけて解決します',
    gameplayAudio: 'オーディオと操作',
    sound: '効果音',
    soundDesc: '文字選択時やクリア時の心地よいサウンド',
    music: 'BGM (音楽)',
    musicDesc: 'プレイ中の落ち着いたバックグラウンドミュージック',
    vibration: '振動フィードバック',
    vibrationDesc: '正しい文字を結んだときの振動',
    appearance: '外観とアクセシビリティ',
    darkMode: 'ダークテーマ',
    highContrast: 'ハイコントラスト',
    highContrastDesc: '文字枠をくっきりさせ視認性を高めます',
    largeText: '文字を大きく',
    reducedMotion: 'アニメーション軽減',
    language: '言語 (Language)',
    languageSubtitle: 'ゲーム画面とパズルの言語を設定します',
    about: 'Word Huntについて',
    dangerZone: '進行状況の管理',
    resetProgress: 'レベル1にリセット',
    resetConfirm: 'すべての進行状況を初期化してレベル1からやり直しますか？',
    resetSuccess: '進行状況をレベル1にリセットしました。',
    dailyStreak: '連続ログイン日数',
    claimReward: '報酬を受け取る',
    streakReward: 'ストリーク報酬',
    puzzlesSolved: 'クリアしたパズル',
    totalWords: '発見した単語',
    totalStars: '総スター数',
    bestStreak: '最長ストリーク',
    accuracy: '正解率',
    saveSuccessful: '進行状況を保存しました',
    watchAdForHint: '広告を見てヒント獲得 (+1)',
    buyHints: 'ヒントパック購入',
    back: '戻る',
    tapToLearn: '見つけた単語をタップして意味と例文を学習！',
    tutorialSwipe: '文字を指でなぞって単語を見つけましょう：',
    howToPlay: '遊び方',
    gotIt: '了解！',
    copied: 'コピーしました！',
    challenges: 'チャレンジ',
    challengeSubtitle: '大きなマス目と特別な報酬がもらえる限定遠征',
    currentChallenge: '現在のチャレンジ',
    gridSize: 'グリッドサイズ',
    difficulty: '難易度',
    reward: '報酬',
    playChallenge: '遠征に出発',
    challengeCompleted: 'チャレンジ完了',
    hints: 'ヒント',
    collectionSubtitle: 'あなたのバッジ、実績、記録、統計データ',
    unlocked: '獲得済み',
    of: '/',
    definition: '意味',
    example: '例文',
    freeHints: '無料',
    adHint: '動画広告'
  },
  ko: {
    appName: 'WORD HUNT',
    tagline: '찾고. 배우고. 탐험하라.',
    play: '플레이',
    dailyPuzzle: '데일리 퍼즐',
    collection: '컬렉션',
    achievements: '도전 과제',
    awards: '트로피',
    records: '기록',
    streak: '연속 일수',
    settings: '설정',
    settingsSubtitle: '소리, 진동, 테마 및 언어',
    profile: '프로필',
    shop: '상점',
    removeAds: '광고 제거',
    privacy: '개인정보처리방침',
    terms: '이용약관',
    restorePurchases: '구매 복원',
    world: '월드',
    level: '레벨',
    levelComplete: '레벨 완료!',
    nextLevel: '다음 레벨',
    share: '공유하기',
    wordsFound: '찾은 단어',
    bonusXp: '보너스 XP',
    stars: '별',
    hintLetter: '첫 글자 표시',
    hintWord: '단어 공개',
    hintAuto: '자동 해결',
    hintLetterDesc: '숨겨진 단어의 시작 글자를 표시합니다',
    hintWordDesc: '단어 목록 중 하나를 알려줍니다',
    hintAutoDesc: '단어 하나를 자동으로 찾아 해결합니다',
    gameplayAudio: '오디오 및 조작',
    sound: '효과음',
    soundDesc: '단어 선택 및 클리어 사운드',
    music: '배경음악',
    musicDesc: '플레이 중 편안한 배경 멜로디',
    vibration: '진동 피드백',
    vibrationDesc: '올바른 글자 연결 시 햅틱 진동',
    appearance: '화면 및 접근성',
    darkMode: '다크 모드',
    highContrast: '고대비 모드',
    highContrastDesc: '가독성을 높이는 뚜렷한 글자 테두리',
    largeText: '큰 글꼴',
    reducedMotion: '애니메이션 줄이기',
    language: '언어 (Language)',
    languageSubtitle: '게임 화면 및 단어 퍼즐의 언어를 선택하세요',
    about: 'Word Hunt 정보',
    dangerZone: '게임 진행 데이터',
    resetProgress: '레벨 1로 초기화',
    resetConfirm: '모든 진행 상황을 초기화하고 레벨 1부터 다시 시작하시겠습니까?',
    resetSuccess: '진행 상황이 레벨 1로 초기화되었습니다.',
    dailyStreak: '연속 일수',
    claimReward: '보상 받기',
    streakReward: '연속 보상',
    puzzlesSolved: '완료한 퍼즐',
    totalWords: '찾은 단어 총합',
    totalStars: '획득한 별 총합',
    bestStreak: '최고 연속 기록',
    accuracy: '정확도',
    saveSuccessful: '진행 상황 저장 완료',
    watchAdForHint: '광고 보고 힌트 받기 (+1)',
    buyHints: '힌트 패키지',
    back: '뒤로',
    tapToLearn: '찾은 단어를 탭하여 뜻과 예문을 확인하세요!',
    tutorialSwipe: '글자를 스와이프하여 단어를 완성하세요:',
    howToPlay: '게임 방법',
    gotIt: '확인!',
    copied: '복사되었습니다!',
    challenges: '도전 과제 & 탐험',
    challengeSubtitle: '더 큰 그리드와 특별한 보상이 주어지는 한정 원정',
    currentChallenge: '현재 챌린지',
    gridSize: '그리드 크기',
    difficulty: '난이도',
    reward: '보상',
    playChallenge: '원정 시작',
    challengeCompleted: '챌린지 완료',
    hints: '힌트',
    collectionSubtitle: '나의 배지, 트로피, 마일스톤 및 통계',
    unlocked: '달성',
    of: '/',
    definition: '단어 뜻',
    example: '예문',
    freeHints: '무료',
    adHint: '광고'
  },
  hi: {
    appName: 'WORD HUNT',
    tagline: 'खोजें. सीखें. अन्वेषण करें.',
    play: 'खेलें',
    dailyPuzzle: 'दैनिक पहेली',
    collection: 'संग्रह',
    achievements: 'उपलब्धियां',
    awards: 'पुरस्कार',
    records: 'रिकॉर्ड',
    streak: 'दैनिक स्ट्रीक',
    settings: 'सेटिंग्स',
    settingsSubtitle: 'ध्वनि, कंपन, थीम और भाषा',
    profile: 'प्रोफ़ाइल',
    shop: 'दुकान',
    removeAds: 'विज्ञापन हटाएं',
    privacy: 'गोपनीयता नीति',
    terms: 'नियम व शर्तें',
    restorePurchases: 'खरीद पुनर्स्थापित करें',
    world: 'विश्व',
    level: 'स्तर',
    levelComplete: 'स्तर पूर्ण!',
    nextLevel: 'अगला स्तर',
    share: 'साझा करें',
    wordsFound: 'मिले हुए शब्द',
    bonusXp: 'बोनस XP',
    stars: 'सितारे',
    hintLetter: 'पहला अक्षर दिखाएं',
    hintWord: 'शब्द बताएं',
    hintAuto: 'स्वतः हल करें',
    hintLetterDesc: 'छिपे हुए शब्द के पहले अक्षर को इंगित करता है',
    hintWordDesc: 'सूची से एक लक्ष्य शब्द दिखाता है',
    hintAutoDesc: 'ग्रिड में एक शब्द को स्वचालित रूप से ढूंढता है',
    gameplayAudio: 'ध्वनि और नियंत्रण',
    sound: 'ध्वनि प्रभाव',
    soundDesc: 'अक्षर चुनने और पहेली हल करने पर ध्वनि',
    music: 'संगीत',
    musicDesc: 'खेलते समय शांतिदायक पृष्ठभूमि संगीत',
    vibration: 'कंपन (हैप्टिक)',
    vibrationDesc: 'सही अक्षर चुनने पर हल्का कंपन',
    appearance: 'दिखावट और थीम',
    darkMode: 'डार्क मोड',
    highContrast: 'उच्च कंट्रास्ट',
    highContrastDesc: 'स्पष्ट अक्षरों के लिए अधिकतम कंट्रास्ट',
    largeText: 'बड़ा टेक्स्ट',
    reducedMotion: 'कम एनिमेशन',
    language: 'भाषा (Language)',
    languageSubtitle: 'इंटरफ़ेस और पहेलियों के लिए भाषा चुनें',
    about: 'वर्ड हंट के बारे में',
    dangerZone: 'गेम प्रगति',
    resetProgress: 'स्तर 1 पर रीसेट करें',
    resetConfirm: 'क्या आप पूरी प्रगति रीसेट करके स्तर 1 से शुरू करना चाहते हैं?',
    resetSuccess: 'प्रगति स्तर 1 पर रीसेट हो गई।',
    dailyStreak: 'दैनिक स्ट्रीक',
    claimReward: 'इनाम पाएं',
    streakReward: 'स्ट्रीक पुरस्कार',
    puzzlesSolved: 'हल की गई पहेलियां',
    totalWords: 'कुल शब्द',
    totalStars: 'कुल सितारे',
    bestStreak: 'सर्वश्रेष्ठ स्ट्रीक',
    accuracy: 'सटीकता',
    saveSuccessful: 'प्रगति सुरक्षित की गई',
    watchAdForHint: 'विज्ञापन देखें (+1 संकेत)',
    buyHints: 'संकेत पैक',
    back: 'वापस',
    tapToLearn: 'अर्थ और उदाहरण देखने के लिए मिले शब्द पर टैप करें!',
    tutorialSwipe: 'शब्द बनाने के लिए अक्षरों पर स्वाइप करें:',
    howToPlay: 'कैसे खेलें',
    gotIt: 'समझ गया!',
    copied: 'कॉपी किया गया!',
    challenges: 'चुनौतियां',
    challengeSubtitle: 'बड़ी ग्रिड और विशेष पुरस्कारों वाले विशेष अभियान',
    currentChallenge: 'वर्तमान चुनौती',
    gridSize: 'ग्रिड आकार',
    difficulty: 'कठिनाई',
    reward: 'इनाम',
    playChallenge: 'अभियान खेलें',
    challengeCompleted: 'चुनौती पूर्ण',
    hints: 'संकेत',
    collectionSubtitle: 'आपके बैज, ट्रॉफियां, मील के पत्थर और आंकड़े',
    unlocked: 'अनलॉक',
    of: 'में से',
    definition: 'अर्थ',
    example: 'उदाहरण',
    freeHints: 'निःशुल्क',
    adHint: 'विज्ञापन'
  }
};

export function getTranslation(lang: LanguageCode | string | undefined, key: string): string {
  const code = (lang as LanguageCode) || 'en';
  const dict = TRANSLATIONS[code] || TRANSLATIONS.en;
  return dict[key] || TRANSLATIONS.en[key] || key;
}
